#!/bin/sh
#
# Copyright 1999, TaBE Project, All Rights Reserved.
# Copyright 1999, Pai-Hsiang Hsiao, All Rights Reserved.
#
# $Id: tsipackdb,v 1.1 2000/12/09 09:14:30 thhsieh Exp $
#

PREFIX=/usr/local/BerkeleyDB/bin/

TMP=/tmp/.XXXTSITRANSIT

${PREFIX}/db_dump $1 > ${TMP}
mv $1 $1.orig
${PREFIX}/db_load -f ${TMP} $1
rm -rf ${TMP}

